def call (num):
     print ('num')
call ('num')
print ('num=8')
print ('num=8')    
print ('num=0')
print ('num=0')
print ('num=5')
print ('num=5')
print ('num=5')
print ('num=3')
print ('num=5')
print ('num=3')
print ('num=5')